# MAC MUSL BUILD
#env CC=arm-linux-musleabihf-gcc GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 go build -o MDroid-Core-MUSL ./

# LINUX MUSL BUILD
#env CC=arm-linux-musleabihf-gcc GOOS=linux GOARCH=arm GOARM=7 CGO_ENABLED=1 go build -o ./bin/MDroid-Core-MUSL ./

# REGULAR GO BUILD
#go build -o ./bin/MDroid-Core

language: go

go:
- "1.10"
- 1.11
- 1.12

before_install:
  - go get -u -v "github.com/gorilla/mux"
  - go get -u -v "github.com/parnurzeal/gorequest"
  - go get -u -v "github.com/tarm/serial"

install:
  - go get -t -v ./...

notifications:
  email:
    recipients: quinn@quinncasey.com
    on_success: change
    on_failure: always

env:
  - GOOS=linux CGO=1
  - GOOS=linux CGO=0
  - GOOS=linux GOARCH=arm
  - GOOS=linux GOARCH=mips
  - GOOS=linux GOARCH=mipsle
  - GOOS=windows GOARCH=386