language: go
go:
  - 1.10
  - 1.11
  - 1.12
install:
  - go get github.com/MrDoctorKovacic/MDroid-Core
notifications:
  email:
    recipients: quinn@quinncasey.com
    on_success: change
    on_failure: always